In [8]:
print("hello")

hello

In [9]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("../Data/SalesData.csv")
df.head()

,Order_ID,Date,Customer_ID,Product_Category,Product_Name,Quantity,Unit_Price_INR,Total_Sales_INR,Payment_Method,Delivery_Status,Review_Rating,Review_Text,State,Country
0,ORD100000,20-01-2025,CUST2796,Home & Kitchen,Cookware Set,2,25574.41,51148.82,Credit Card,Returned,1,Waste of money,Sikkim,India
1,ORD100001,28-08-2025,CUST9669,Beauty,Hair Dryer,1,19361.41,19361.41,Debit Card,Returned,5,Excellent product!,Telangana,India
2,ORD100002,27-02-2025,CUST5808,Electronics,Tablet,3,38476.22,115428.66,Cash on Delivery,Delivered,3,Fair deal,Nagaland,India
3,ORD100003,24-02-2025,CUST5889,Electronics,Headphones,5,38145.72,190728.60,Credit Card,Delivered,5,Highly recommend!,Assam,India
4,ORD100004,15-06-2025,CUST9005,Clothing,Saree,5,45940.98,229704.90,UPI,Delivered,5,Highly recommend!,Odisha,India

In [11]:
df.columns

Index(['Order_ID', 'Date', 'Customer_ID', 'Product_Category', 'Product_Name',
       'Quantity', 'Unit_Price_INR', 'Total_Sales_INR', 'Payment_Method',
       'Delivery_Status', 'Review_Rating', 'Review_Text', 'State', 'Country'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          15000 non-null  object
 1   Date              15000 non-null  object
 2   Customer_ID       15000 non-null  object
 3   Product_Category  15000 non-null  object
 4   Product_Name      15000 non-null  object
 5   Quantity          15000 non-null  int64
 6   Unit_Price_INR    15000 non-null  float64
 7   Total_Sales_INR   15000 non-null  float64
 8   Payment_Method    15000 non-null  object
 9   Delivery_Status   15000 non-null  object
 10  Review_Rating     15000 non-null  int64
 11  Review_Text       15000 non-null  object
 12  State             15000 non-null  object
 13  Country           15000 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.6+ MB

In [ ]:
# df["Date"] = df["Date"].dt.strftime("%d-%m-%Y")

In [13]:
print(df["Date"].head())

0    20-01-2025
1    28-08-2025
2    27-02-2025
3    24-02-2025
4    15-06-2025
Name: Date, dtype: object

In [14]:
df.isnull().sum()

Order_ID            0
Date                0
Customer_ID         0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price_INR      0
Total_Sales_INR     0
Payment_Method      0
Delivery_Status     0
Review_Rating       0
Review_Text         0
State               0
Country             0
dtype: int64

In [17]:
df.describe()

           Quantity  Unit_Price_INR  Total_Sales_INR  Review_Rating
count  15000.000000    15000.000000     15000.000000   15000.000000
mean       2.984667    24955.313715     74544.120233       3.040133
std        1.422826    14401.316925     59369.654155       1.411048
min        1.000000      202.570000       204.050000       1.000000
25%        2.000000    12512.937500     27087.852500       2.000000
50%        3.000000    24878.755000     57293.570000       3.000000
75%        4.000000    37496.170000    112188.600000       4.000000
max        5.000000    49994.430000    249955.500000       5.000000

In [22]:
df.duplicated().any()

np.False_

In [15]:
for i in df.columns:
    print(i, ":", df.nunique()[i])

Order_ID : 15000
Date : 365
Customer_ID : 7259
Product_Category : 5
Product_Name : 25
Quantity : 5
Unit_Price_INR : 14981
Total_Sales_INR : 14988
Payment_Method : 4
Delivery_Status : 3
Review_Rating : 5
Review_Text : 25
State : 28
Country : 1

In [23]:
df.drop(columns=["Country"], inplace=True)

## Data Preprocessing Summary

The following preprocessing steps were performed to prepare the dataset for analysis:

- No missing (null) values were found in the dataset.
- The **Date** column was converted from the **object** data type to **datetime** for accurate date-based analysis.
- No duplicate records were found in the dataset.
- The **Country** column was removed because it contained only a single unique value (**India**), making it non-informative for analysis.

### Conclusion

The dataset has been successfully preprocessed and is clean, consistent, and ready for exploratory data analysis (EDA) and further analytical tasks.